title: Davenowell's Blog
author: Davenowell
email: davenowell@github.com
description: > # this means to ignore newlines until "baseurl:"
  The blog of blogs.

# social links
github_username:  davenowell # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
